contexts:
    machine-core:
      brokers:
        - localhost:19092
    sim-ny:
      brokers:
        - localhost:19192
    sim-la:
      brokers:
        - localhost:19292
    user1:
      brokers:
        - localhost:19092
      sasl:
        enabled: true
        username: user1
        password: password1
    user2:
      brokers:
        - localhost:19092
      sasl:
        enabled: true
        username: user2
        password: password2
    user3:
      brokers:
        - localhost:19102
      sasl:
        enabled: true
        username: user3
        password: password3